### PR TITLE
Fix and add settings for edge labels

### PR DESCRIPTION
**Pull request by chenghuzi**
1. fix missing edge label font alpha
2. add background color settings for edge labels

### CODE REVIEW

**Comment by paulbrodersen** [comment]
Hey @chenghuzi , thanks for the PR. 

First of all, great catch regarding `edge_label_font_alpha`. 

Secondly, there already is a way to set the background color, namely through the `edge_label_bbox` argument. The default is 

                edge_label_bbox = dict(boxstyle='round',
                                       ec=(1.0, 1.0, 1.0),
                                       fc=(1.0, 1.0, 1.0))

where `box_style`, `ec` (edge color) and `fc` (face color) are arguments inherited from matplotlib's bounding box. There shouldn't be two ways (which could be conflicting) to control the same parameter. I hence see the following options:

1. We leave it as it is. You remove the 2nd part of your PR and I accept the rest, i.e. the part regarding the font alpha setting. 

2. We scrap my approach and expand your solution to include the other  
bbox parameters, i.e. add `edge_label_bbox_facecolor` (your background color argument), `edge_label_bbox_edgecolor` and `edge_label_bbox_boxstyle to the list of parameters, and construct the `edge_label_bbox` internally based on the function input. 
**Pros:** Very explicit, all possible ways to amend the plots are documented. 
**Cons:** We are handling parameters that could be passed "as is" to matplotlib. Matplotlib might expand the capabilities of text objects in the future and then netgraph would then need to change and handle these new parameters. Lots of code to maintain. 

3. We enable keyword argument pass trough to matplotlib and scrap all superfluous arguments. Matplotlib does exactly the same thing in their `matplotlib.pyplot.text` with their `font_dict` argument (see docs [here](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.text.html)). 
**Pros:** Less code to maintain. 
**Cons:** Not very explicit. 

# Question: 
Personally, I am a fan of option 3, but I also know matplotlib pretty well. However, I am not representative of my target audience, but you are. Hence: 

**Given the docs to `matplotlib.pyplot.text` linked above, would you have been able to quickly find out how to set the label background color of a text box?**

**Comment by paulbrodersen** [comment]
On an unrelated note, I just saw on your github that you were interested in feedback alignment. Is that still something you work on? Tim (the first author) was my mentor during my PhD and Colin (last author) was and still is my supervisor.

**Comment by chenghuzi** [comment]
Hi @paulbrodersen , I think it might be hard for users who are not familiar with the implementation of edge label, i.e. `ax.text`, to set the label background color through matplotlib parameters. But the need to set edge label bg color is obvious: white bg color of edge labels sometimes make it hard to recognize which belongs to which. So I prefer option2. If you're ok with this, I'll try to fix it.

**Comment by chenghuzi** [comment]
> On an unrelated note, I just saw on your github that you were interested in feedback alignment. Is that still something you work on? Tim (the first author) was my mentor during my PhD and Colin (last author) was and still is my supervisor.

FA is great work! And so is recent FA with weight mirror.
Yes one of my research focuses is biologically plausible learning in NNs and FA is something I'm working on and trying to integrate into a larger framework.

**Comment by chenghuzi** [comment]
I see, I just misunderstood the `edge_label_bbox` parameter and thought it's share with node labels. I'll remove part 2.

**Pull request merged**
